### ISSUE TITLE
Implement load averages for Windows

### ISSUE THREAD

**Issue by ycombinator** [elastic/gosigar#114]
This would help resolve https://github.com/elastic/beats/issues/9944.

Currently, this method is not implemented:

https://github.com/elastic/gosigar/blob/7bed2391b1d10309feac210aee9df44e8db2d060/sigar_windows.go#L57-L59

This is likely because the analogous function in the C Sigar library is also not implemented:

https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/src/os/win32/win32_sigar.c#L1140-L1149

However, https://github.com/boundary/sigar, which is a fork of https://github.com/hyperic/sigar has an implementation for the above function:

https://github.com/boundary/sigar/blob/a6c61edf8c64e013411e8c9d753165cd03102c6e/src/os/win32/win32_sigar.c#L1084-L1125

Perhaps we could reference this implementation and port it over?

Related: #107

**Comment by cachedout** [comment]
@ycombinator Per our discussion yesterday, I am going to close this. Let me know if you think that's incorrect.
