### ISSUE TITLE
build failed with darwin_386

### ISSUE THREAD

**Issue by godcong** [elastic/gosigar#135]
this is the failed log:

##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:20:11: cpuUsage.Get undefined (type Cpu has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:30:13: cpuUsage.Get undefined (type Cpu has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:49:10: l.Get undefined (type LoadAverage has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:55:10: m.Get undefined (type Mem has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:61:10: s.Get undefined (type Swap has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:67:10: p.Get undefined (type HugeTLBPages has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/concrete_sigar.go:79:11: fd.Get undefined (type FDUsage has no field or method Get)
##[error]/Users/runner/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/sigar_darwin_386.go:11:12: undefined: sysctlbyname

you can see on this link:
https://github.com/glvd/accipfs/runs/573143054?check_suite_focus=true

i build my project with windows,linux,darwin
but only the darwin_386 was failed.

**Comment by fllaca** [comment]
@godcong hi! did you fix this? it's happening to me too

**Comment by godcong** [comment]
> @godcong hi! did you fix this? it's happening to me too
I posted it for a while、nobody cares about this. so i closed it.

I have not compiled the x86 version
