### ISSUE TITLE
`go test` fails on a clean windows install

### ISSUE THREAD

**Issue by eonarheim** [elastic/gosigar#14]
Howdy! 

I'm fairly new to go so help me out if I'm completely in left field on this one.

Running a plain `go test` on a clean windows install of gosigar fails. I believe that this is due to platform differences between windows and *nix systems that are not accounted for in the `sigar_interface_test.go` and the `concrete_sigar_test.go` outlined in detail in this pull request: elastic/gosigar/pull/13

One example is that executables in windows need a ".exe" suffix whereas in a *nix system this need not be the case 

Apologies for the rough cmd window formatting :)
```bash
←[90mC:/Projects/GoWorkspace/src/github.com/elastic/gosigar/sigar_interface_
test.go:100←[0m

  ←[91mExpected
      <[]string | len:2, cap:2>: ["go", "ginkgo"]
  to contain element matching
      <string>: go.exe←[0m
```

Perhaps an appveyor + travis CI server would help illuminate these types of issues by building and running tests on all environments gosigar is deployed :)

**Comment by ruflin** [comment]
There is already a travis build running: https://travis-ci.org/elastic/gosigar It would be great if we could also add appveyor for the windows build.

Probably we should also link the Travis build in the README: https://github.com/elastic/gosigar/blob/master/README.md

For the appveyor config it is best to have a look at the file from the beats project: https://github.com/elastic/beats/blob/master/.appveyor.yml

**Comment by andrewkroh** [comment]
`go test` is passing on Windows.

AppVeyor and TravisCI both build this project (and badges added to README).

**Comment by eonarheim** [comment]
Awesome! :smile: :+1:
