### ISSUE TITLE
Get the cpu usage per core in Windows

### ISSUE THREAD

**Issue by monicasarbu** [elastic/gosigar#6]
The following function needs to be implemented.

<pre>
func (self *CpuList) Get() error {
	return notImplemented()
}
</pre>

Getting cpu usage per core under Unix systems is implemented in the PR: https://github.com/elastic/topbeat/pull/130

**Comment by monicasarbu** [comment]
Requested by https://github.com/elastic/topbeat/issues/40 as well.

**Comment by vjsamuel** [comment]
https://github.com/UhuruSoftware/gosigar/blob/master/sigar_windows.go is a possible implementation which we could go for.

**Comment by monicasarbu** [comment]
@vjsamuel Thank you. I'll give it a try and let you know if it works.

**Comment by vjsamuel** [comment]
How do you generally test in windows environment? If I know how to do that then I can try it out myself.

**Comment by monicasarbu** [comment]
You can use the virtual machine from https://github.com/elastic/winlogbeat/blob/master/Vagrantfile and then install gcc by using choco install mingw64.

**Comment by andrewkroh** [comment]
@vjsamuel FYI we have an updated Vagrantfile in the [elastic/beats](https://github.com/elastic/beats/blob/master/Vagrantfile) repo that has the development environment fully setup for compiling Topbeat and gosigar. It should be as simple as:

```
vagrant up
vagrant ssh
cd C:\Gopath\src\github.com\elastic\beats\topbeat
go build
```
