### ISSUE TITLE
Socket test failing in Beats

### ISSUE THREAD

**Issue by namrata-ibm** [elastic/gosigar#73]
While building [Beats](https://github.com/elastic/beats) on a Big Endian system, one of the socket related test fails which uses Go sigar code `sys/linux/inetdiag.go`. Will it be possible to add Big Endian support in Go sigar ?

**Comment by namrata-ibm** [comment]
Any update on this? 
@ruflin / @knz Could you please have a look?

**Comment by ruflin** [comment]
@andrewkroh is probably the better person here to give some feedback.

**Comment by andrewkroh** [comment]
Which test is failing? Can you provide the output?

The endianness is hardcoded in a few places IRRC. The endianness could be extracted to a variable and populated based on the detected endianness of the machine.

**Comment by namrata-ibm** [comment]
While executing `go test -v github.com/elastic/beats/metricbeat/module/system/socket` from `metricbeat` , the execution hangs at `TestFetch`:

```
=== RUN   TestHashSet
--- PASS: TestHashSet (0.00s)
=== RUN   TestListenerTable
--- PASS: TestListenerTable (0.00s)
=== RUN   TestData
--- SKIP: TestData (0.00s)
        data_generator.go:38: Skip data generation tests
=== RUN   TestFetch
```

If I modify the `serialize` and `ParseInetDiagMsg` functions from [inetdiag.go](https://github.com/elastic/beats/blob/master/vendor/github.com/elastic/gosigar/sys/linux/inetdiag.go) file, to change the occurrences of `binary.LittleEndian` to `binary.BigEndian`, the test passes.

**Comment by namrata-ibm** [comment]
@andrewkroh, could you please have a look at the above?

**Comment by andrewkroh** [comment]
Oh, so it's a test in Metricbeat.

I think that package should have a variable like

`var endianness binary.ByteOrder`

and update all hard-coded places to use the variable.

Then have an init() function that detects the endian.
```
// NOT TESTED
func init() {
        var i int32 = 0x1
	v := (*[4]byte)(unsafe.Pointer(&i))
	if v[0] == 0 {
		endianness = binary.BigEndian
	} else {
		endianness = binary.LittleEndian
	}
}
```

WDYT?

**Comment by namrata-ibm** [comment]
@andrewkroh, ya this looks good.

**Comment by namrata-ibm** [comment]
Can this change be merged? @andrewkroh, the above patch works fine on little and big endian.

**Comment by Nayana-ibm** [comment]
@andrewkroh As you suggested in your [comment](https://github.com/elastic/gosigar/issues/73#issuecomment-306795092), we have worked on adding big endian support for gosigar. 
Raised PR #98 . Could you please review?

**Comment by Nayana-ibm** [comment]
As #100 is merged, Can you please update beats source code to have latest commit of gosigar? This will fix the issues with big endian.

**Comment by ruflin** [comment]
@andrewkroh Should we do a gosigar release?

**Comment by Nayana-ibm** [comment]
@andrewkroh @ruflin Can Beats use latest stable of gosigar ? This will fix the issues with big endian.

**Comment by andrewkroh** [comment]
It looks like v0.9.0 is being used by Beats on master and 6.3 branches. See [vendor.json](https://github.com/elastic/beats/blob/fabdf0b6094370fd9b32e61286b685396448d9d8/vendor/vendor.json#L674-L713). v0.9.0 includes the endian changes.

**Comment by Nayana-ibm** [comment]
Thanks. Will wait for 6.3 tag
