### ISSUE TITLE
Merging Changes back to Cloudfoundry/gosigar

### ISSUE THREAD

**Issue by zachgersh** [elastic/gosigar#80]
Hey All,

Wanted to stop by and compliment the amount of work that has been done on `gosigar` - its great. Would love to discuss how we can get these two libraries merged back together. For now, I am going to add some of the same windows support that you all have included here back to cloudfoundry/gosigar.

**Comment by tsg** [comment]
Hi @zachgersh, sorry for the late reply, the GH notification got lost in my inbox and I only noticed this now.

We're glad to see that the upstream gosigar is becoming active again, and we'll be following it to see if it makes sense for us to re-base on top of it. I'm not sure if we can allocate resources to make the merge happen, but happy to discuss further. Shoot me an email at first-name@elastic.co if you want us to organise a quick chat on it.

**Comment by zachgersh** [comment]
Hey @tsg - appreciate you getting back to me (no problem on losing the notification, happens to me all the time).

We on CF can totally get all of your code back into the upstream and would allocate time to do it - If you are ok with that just let me know here and we can start to make that happen.

Would also be nice to figure out how to collaborate on this repo more as it seems like an important part of what elastic is doing.

**Comment by tsg** [comment]
Yes, that's ok with us, we're happy to contribute back to the upstream. Thanks!
