### ISSUE TITLE
Memory ActualUsed should be different from Memory Used

### ISSUE THREAD

**Issue by jiang1095** [elastic/gosigar#87]
https://github.com/elastic/gosigar/blob/8620c67b07d4fa26515247338c0a228369942840/sigar_linux_common.go#L74-L75

`ActualUsed` and `Used` should be different.

**Comment by ruflin** [comment]
@jiang1095 Is that what you are looking for? https://github.com/elastic/gosigar/pull/82

**Comment by jiang1095** [comment]
@ruflin yes, this PR can fix my problem.
