### ISSUE TITLE
Does not build on FreeBSD

### ISSUE THREAD

**Issue by girgen** [elastic/gosigar#89]
When building elastic/beats, that uses version v0.6.0 of gosigar, I get this: `# github.com/elastic/beats/vendor/github.com/elastic/gosigar
../../src/github.com/elastic/beats/vendor/github.com/elastic/gosigar/sigar_freebsd.go:111: (*ProcTime).Get redeclared in this block
        previous declaration at ../../src/github.com/elastic/beats/vendor/github.com/elastic/gosigar/sigar_linux_common.go:277:6
`

Just commenting out the `(*ProcTime).Get` function in gosigar_linux_common.go fixes the problem for me. Perhaps the fix is a easy as moving that function from `gosigar_linux_common.go` to `gosigar_linux.go`?

Adding the patch in master does regarding `gosigar_stub.go`  does *not* help.

**Comment by ruflin** [comment]
What you suggest above should work I think. The naming of `sigar_linux_common` is a bit misleading as it builds also on freebsd. Could you open a PR with this change then we also see what CI thinks.

@andrewkroh Thoughts?

**Comment by andrewkroh** [comment]
I think the only change that is needed is to remove these three lines.

https://github.com/elastic/gosigar/blob/36e30f86fab34ac5e56a59cfe80929d65babb00d/sigar_freebsd.go#L111-L113

This should not have been added because the common implementation is used.

**Comment by girgen** [comment]
Ah, excellent. This actually makes `ps` **work** as well. :-)

I Created a new pull request #91
